Repository datavisyn/visyn_core, pull requests merged in 2023-07, with the labels that each got.

#57 Release 3.0.1
  package.json
  src/vis/sidebar/CategoricalColumnSelect.tsx
  src/vis/sidebar/NumericalColumnSelect.tsx
  visyn_core/id_mapping/idtype_api.py
Labels: release: patch

#58 feat: propagate `bottom` prop to `AboutAppModal`
  src/app/header/AboutAppModal.tsx
  src/app/header/ConfigurationMenu.tsx
Labels: release: minor, type: bug

#2 Add basic telemetry infrastructure
  README.md
  deploy/telemetry/dashboards.yaml
  deploy/telemetry/dashboards/fastapi-observability.json
  deploy/telemetry/dashboards/node-exporer-full.json
  deploy/telemetry/docker-compose.telemetry.yml
  deploy/telemetry/grafana/datasource.yml
  deploy/telemetry/grafana_agent/agent.yaml
  deploy/telemetry/otel-collector/otel-collector-config.yaml
  deploy/telemetry/prometheus/prometheus.yml
  docs/TELEMETRY.md
  requirements.txt
  setup.py
  visyn_core/middleware/fastapi_metrics_middleware.py
  visyn_core/server/visyn_server.py
  visyn_core/settings/model.py
  visyn_core/telemetry/__init__.py
  visyn_core/tests/fixtures/app.py
  visyn_core/tests/test_telemetry.py
Labels: release: minor, type: deployment, type: feature

#69 feat: add `log_level` config value to settings
  visyn_core/server/visyn_server.py
  visyn_core/settings/model.py
  visyn_core/tests/test_settings.py
Labels: release: minor, type: feature
