Repository datavisyn/visyn_core, pull requests merged in 2023-10, with the labels that each got.

#96 deps: pin werkzeug to 2.3.7
  requirements.txt
Labels: release: patch, type: technical debt

#98 Release 4.1.1
  package.json
  requirements.txt
Labels: release: patch

#35 feat: add derived Taggle for VisynRanking
  src/components/PermissionChooser.styles.ts
  src/components/PermissionChooser.tsx
  src/demo/MainApp.tsx
  src/demo/scoresUtils.ts
  src/ranking/EagerVisynRanking.tsx
  src/ranking/index.ts
  src/ranking/overrides/DatavisynLineUpBuilder.tsx
  src/ranking/overrides/DatavisynTaggle.tsx
  src/ranking/overrides/index.ts
  src/ranking/score/interfaces.ts
  src/ranking/score/utilities.ts
  src/ranking/smiles/SMILESColumn.tsx
  src/ranking/smiles/SMILESColumnBuilder.ts
  src/ranking/smiles/SMILESFilterDialog.tsx
  src/ranking/smiles/SMILESRenderer.tsx
  src/ranking/smiles/index.ts
  src/ranking/smiles/utils.ts
Labels: release: minor, type: feature, type: refactor
