Repository datavisyn/visyn_core, pull requests merged in 2023-08, with the labels that each got.

#68 feat: add oauth2_access_token to User model
  visyn_core/security/model.py
  visyn_core/security/store/alb_security_store.py
  visyn_core/security/store/oauth2_security_store.py
  visyn_core/tests/test_security_login.py
Labels: release: patch, type: feature

#70 deps: update to lineupjs@4.9.0
  package.json
Labels: release: minor, dependencies

#72 deps: Pin mantine/* to 6.0.17
  package.json
Labels: dependencies

#75 Upgrade RDKit to 2023.3.2 and improve tests
  requirements_extras_rdkit.txt
  visyn_core/rdkit/__init__.py
  visyn_core/tests/rdkit/align.svg
  visyn_core/tests/rdkit/maximum_common_substructure.svg
  visyn_core/tests/rdkit/maximum_common_substructure_inconsistent.svg
  visyn_core/tests/rdkit/murcko.svg
  visyn_core/tests/rdkit/similarity_CCCC_CC.svg
  visyn_core/tests/rdkit/similarity_CC_CCCC.svg
  visyn_core/tests/rdkit/substructure.svg
  visyn_core/tests/rdkit/valid_C.svg
  visyn_core/tests/rdkit/valid_O.svg
  visyn_core/tests/rdkit/valid_OO.svg
  visyn_core/tests/rdkit/valid_[He].svg
  visyn_core/tests/test_rdkit_img.py
Labels: release: minor, dependencies

#73 feat: add functionality to verify token from ALB and add on_user_loaded hook
  visyn_core/security/manager.py
  visyn_core/security/store/alb_security_store.py
  visyn_core/settings/model.py
  visyn_core/tests/test_security_login.py
Labels: release: patch, type: feature

#77 deps: change pyjwt to pyjwt[crypto]
  requirements.txt
Labels: release: patch, dependencies

#81 feat: added ability to define multiple email fields in alb and oauth2 stores
  src/app/login/VisynLoginMenu.tsx
  visyn_core/security/store/alb_security_store.py
  visyn_core/security/store/oauth2_security_store.py
  visyn_core/settings/model.py
  visyn_core/tests/test_security_login.py
  visyn_core/tests/test_settings.py
Labels: release: patch, type: feature

#82 Release 4.0.0
  package.json
  requirements.txt
  requirements_extras_rdkit.txt
  src/app/login/VisynLoginMenu.tsx
  visyn_core/dbmanager.py
  visyn_core/rdkit/__init__.py
  visyn_core/rdkit/img_api.py
  visyn_core/security/manager.py
  visyn_core/security/model.py
  visyn_core/security/store/alb_security_store.py
  visyn_core/security/store/oauth2_security_store.py
  visyn_core/settings/model.py
  visyn_core/tests/rdkit/align.svg
  visyn_core/tests/rdkit/maximum_common_substructure.svg
  visyn_core/tests/rdkit/maximum_common_substructure_inconsistent.svg
  visyn_core/tests/rdkit/murcko.svg
  visyn_core/tests/rdkit/similarity_CCCC_CC.svg
  visyn_core/tests/rdkit/similarity_CC_CCCC.svg
  visyn_core/tests/rdkit/substructure.svg
  visyn_core/tests/rdkit/valid_C.svg
  visyn_core/tests/rdkit/valid_O.svg
  visyn_core/tests/rdkit/valid_OO.svg
  visyn_core/tests/rdkit/valid_[He].svg
  visyn_core/tests/test_rdkit_img.py
  visyn_core/tests/test_security_login.py
  visyn_core/tests/test_settings.py
Labels: release: major
