Repository datavisyn/visyn_core, pull requests merged in 2023-05, with the labels that each got.

#13 Added mantine provider to visyn app provider
  src/app/VisynAppProvider.tsx
  src/app/constants.tsx
  src/app/index.ts
  src/demo/index.initialize.tsx
  src/scss/base/_base.scss
  src/scss/main.scss
  src/scss/vendors/_lineup.scss
Labels: release: minor, type: feature

#28 fix: avoid unmount if client config is reloaded
  src/app/VisynAppProvider.tsx
Labels: release: patch, type: bug

#29 refactor: migrate clientConfig to /api/v1/visyn/clientConfig
  src/app/VisynAppProvider.tsx
  src/base/clientConfig.ts
  visyn_core/server/visyn_server.py
  visyn_core/settings/client_config.py
  visyn_core/settings/model.py
  visyn_core/tests/test_settings.py
Labels: release: patch, type: refactor

#34 Release v2.0.0
  .vscode/settings.json
  cypress/component/component-health-check.cy.tsx
  cypress/support/component.ts
  cypress/tsconfig.json
  package.json
  src/app/VisynAppContext.tsx
  src/app/VisynAppProvider.tsx
  src/app/constants.tsx
  src/app/header/VisynHeader.stories.tsx
  src/app/index.ts
  src/base/clientConfig.ts
  src/demo/index.initialize.tsx
  src/index.ts
  src/phovea_registry.ts
  src/ranking/EagerVisynRanking.tsx
  src/ranking/VisynRanking.tsx
  src/ranking/index.ts
  src/scss/base/_base.scss
  src/scss/main.scss
  src/scss/vendors/_lineup.scss
  src/utils/index.ts
  src/utils/initializeLibrary.ts
  src/vis/LazyVis.tsx
  src/vis/LineupVisWrapper.ts
  src/vis/stories/Iris.stories.tsx
  tests/exports.test.ts
  visyn_core/__init__.py
  visyn_core/server/visyn_server.py
  visyn_core/settings/client_config.py
  visyn_core/settings/model.py
  visyn_core/settings/router.py
  visyn_core/tests/fixtures/app.py
  visyn_core/tests/test_settings.py
Labels: release: major
