Repository datavisyn/visyn_core, pull requests merged in 2023-03, with the labels that each got.

#3 Release 1.0.0
  package.json
Labels: release: major

#6 Fix VisynApp bug
  src/app/VisynApp.tsx
Labels: release: minor, type: bug

#8 Add api/clientConfig to more easily configure the clientConfig
  src/base/clientConfig.ts
  visyn_core/__init__.py
  visyn_core/settings/model.py
  visyn_core/settings/router.py
  visyn_core/tests/test_settings.py
Labels: release: patch, type: feature
