Repository datavisyn/visyn_core, pull requests merged in 2023-09, with the labels that each got.

#83 Set formatter language to English in fromNow util function
  src/utils/fromNow.ts
Labels: release: minor, type: refactor

#86 docs: Add oauth2/keycloak test environment
  deploy/oauth/README.md
  deploy/oauth/docker-compose.yaml
  deploy/oauth/keycloak/master-realm.json
  deploy/oauth/keycloak/master-users-0.json
  deploy/oauth/oauth2-proxy.cfg
Labels: type: docs

#79 feat: add context to visyn view components
  src/views/visyn/demo/VisynDemoView.tsx
  src/views/visyn/interfaces.ts
Labels: release: patch, type: feature

#93 deps: update to Cypress 13.2
  package.json
Labels: release: patch
