Repository datavisyn/visyn_core, pull requests merged in 2023-11, with the labels that each got.

#101 fix: fix storybook by wrapping all Vis in VisProvider
  src/vis/bar/BarChart.tsx
  src/vis/correlation/CorrelationMatrix.tsx
  src/vis/sidebar/VisTypeSelect.tsx
  src/vis/stories/Vis/Bar/BarRandom.stories.tsx
  src/vis/stories/Vis/Correlation/CorrelationIris.stories.tsx
  src/vis/stories/Vis/Heatmap/HeatmapRandom.stories.tsx
  src/vis/stories/Vis/Hexbin/HexbinRandom.stories.tsx
  src/vis/stories/Vis/Raincloud/RaincloudRandom.stories.tsx
  src/vis/stories/Vis/Scatter/ScatterIris.stories.tsx
  src/vis/stories/Vis/Scatter/ScatterRandom.stories.tsx
  src/vis/stories/Vis/Violin/ViolinIris.stories.tsx
Labels: type: refactor

#111 refactor: log entire token payload if no email field matched
  visyn_core/security/store/alb_security_store.py
  visyn_core/security/store/oauth2_security_store.py
Labels: release: patch, type: refactor

#124 deps: add @emotion/react
  package.json
Labels: release: patch, dependencies

#122 fix: language strings
  src/vis/correlation/CorrelationVis.tsx
  src/vis/raincloud/RaincloudGrid.tsx
Labels: release: patch, type: refactor

#117 fix: hide filter if no callback is provided
  src/vis/EagerVis.tsx
  src/vis/VisSidebar.tsx
  src/vis/bar/BarVisSidebar.tsx
  src/vis/scatter/ScatterVisSidebar.tsx
  src/vis/stories/Vis/Scatter/ScatterIris.stories.tsx
  src/vis/violin/ViolinVisSidebar.tsx
Labels: release: patch, type: bug

#123 fix: violin plot x-axis labels misalignment
  src/vis/violin/ViolinVis.tsx
Labels: release: patch, type: bug
