Repository datavisyn/visyn_core, pull requests merged in 2023-12, with the labels that each got.

#127 fix: switch to storybook config from visyn_scripts
  .storybook/main.js
Labels: release: patch, dependencies

#128 test: add `data-testid` to proxy view iframe
  src/views/visyn/proxy/ProxyViewComponent.tsx
Labels: release: patch, type: technical debt

#134 Release 7.0.0
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .storybook/main.js
  package.json
  src/views/visyn/proxy/ProxyViewComponent.tsx
  src/vis/EagerVis.tsx
Labels: release: major

#136 feat: add get_default_postgres_url utility
  visyn_core/settings/model.py
  visyn_core/settings/utils.py
Labels: release: patch, type: feature
