Repository datavisyn/visyn_core, pull requests merged in 2023-04, with the labels that each got.

#16 fix: add data-cy to login username, password and submit
  src/app/login/VisynLoginForm.tsx
Labels: release: patch

#20 Passing data to createScoreColumnFunc in EagerVisynRanking
  src/demo/MainApp.tsx
  src/ranking/EagerVisynRanking.tsx
Labels: type: feature

#21 Add cypress setting to visyn_core for backend adaptions
  visyn_core/server/visyn_server.py
  visyn_core/settings/model.py
Labels: release: patch, type: feature

#22 feat: add `useEvent` hook
  src/hooks/index.tsx
  src/hooks/useEvent.tsx
Labels: release: patch, type: feature

#24 feat: add build date to about dialog
  src/app/header/AboutAppModal.tsx
  src/hooks/useEvent.tsx
Labels: type: feature

#23 feat: disable border in visyn header
  src/app/header/VisynHeader.tsx
Labels: type: feature

#25 Release v1.2.0
  .storybook/preview.js
  package.json
  src/app/VisynApp.tsx
  src/app/header/AboutAppModal.tsx
  src/app/header/BurgerButton.tsx
  src/app/header/BurgerMenu.tsx
  src/app/header/ConfigurationMenu.tsx
  src/app/header/DatavisynLogo.tsx
  src/app/header/UserAvatar.tsx
  src/app/header/UserMenu.tsx
  src/app/header/VisynHeader.stories.tsx
  src/app/header/VisynHeader.tsx
  src/app/header/index.ts
  src/assets/datavisyn_color.svg
  src/demo/MainApp.tsx
  src/demo/scoresUtils.ts
  src/hooks/index.tsx
  src/hooks/useEvent.tsx
  src/ranking/EagerVisynRanking.tsx
  src/ranking/score/index.ts
  src/ranking/score/interfaces.ts
  src/vis/Vis.tsx
  src/vis/VisSidebarWrapper.tsx
  src/vis/bar/BarVis.tsx
  src/vis/bar/BarVisSidebar.tsx
  src/vis/general/layoutUtils.ts
  src/vis/hexbin/HexbinVisSidebar.tsx
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/ScatterVisSidebar.tsx
  src/vis/sidebar/AggregateTypeSelect.tsx
  src/vis/sidebar/CategoricalColumnSelect.tsx
  src/vis/sidebar/ColorSelect.tsx
  src/vis/sidebar/GroupSelect.tsx
  src/vis/sidebar/HexbinOptionSelect.tsx
  src/vis/sidebar/NumericalColumnSelect.tsx
  src/vis/sidebar/SingleColumnSelect.tsx
  src/vis/sidebar/VisTypeSelect.tsx
  src/vis/violin/ViolinVis.tsx
  src/vis/violin/ViolinVisSidebar.tsx
  visyn_core/id_mapping/idtype_api.py
  visyn_core/server/visyn_server.py
  visyn_core/settings/model.py
Labels: release: minor

#26 Migrate clientConfig to Pydantic models
  src/app/VisynAppContext.tsx
  src/app/VisynAppProvider.tsx
  src/app/header/VisynHeader.stories.tsx
  src/base/clientConfig.ts
  visyn_core/__init__.py
  visyn_core/server/visyn_server.py
  visyn_core/settings/client_config.py
  visyn_core/settings/router.py
  visyn_core/tests/fixtures/app.py
  visyn_core/tests/test_settings.py
Labels: release: major, type: refactor
