Repository datavisyn/visyn_core, pull requests merged in 2024-11, with the labels that each got.

#602 feat(vis-type: scatter): Add log scale option for axes
  src/vis/general/utils.ts
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/ScatterVisSidebar.tsx
  src/vis/scatter/interfaces.ts
  src/vis/scatter/useData.tsx
  src/vis/scatter/useDataPreparation.ts
  src/vis/scatter/useLayout.tsx
  src/vis/scatter/utils.ts
  src/vis/stories/Vis/Scatter/ScatterIris.stories.tsx
Labels: vis-type: scatter

#621 fix: exports in general vis
  src/vis/general/index.ts
  src/vis/general/layoutUtils.ts
Labels: type: bug

#620 Added `useAnimatedTransform` hook
  src/vis/vishooks/hooks/VisHooks.stories.tsx
  src/vis/vishooks/hooks/index.ts
  src/vis/vishooks/hooks/useAnimatedTransform.ts
Labels: type: feature

#625 feat: add `GenomeNavigation` class to util package
  src/utils/GenomeNavigation.ts
  src/utils/index.ts
Labels: release: minor, type: feature

#633 Refactored single subplot log scaling
  src/vis/scatter/useLayout.tsx
  src/vis/stories/Vis/Scatter/ScatterIris.stories.tsx
  src/vis/stories/fetchIrisData.tsx
Labels: release: patch, type: bug

#639 feat(icons): add new array column icons
  src/icons/Icons.tsx
Labels: type: feature
