Repository datavisyn/visyn_core, pull requests merged in 2024-09, with the labels that each got.

#495 deps: upgrade deps to Sep 2024
  package.json
  requirements.txt
Labels: release: major, dependencies

#439 feat: update to visyn_scripts 11
  .github/workflows/release.yml
  cypress/tsconfig.json
  package.json
  src/app/VisynApp.tsx
  src/app/VisynAppContext.tsx
  src/app/header/AboutAppModal.tsx
  src/app/header/ConfigurationMenu.tsx
  src/app/header/UserMenu.tsx
  src/app/login/UserStoreUIMap.tsx
  src/app/login/VisynLoginMenu.tsx
  src/base/ajax.ts
  src/base/event.ts
  src/demo/MainApp.tsx
  src/demo/index.initialize.tsx
  src/hooks/useSetRef.ts
  src/hooks/useVisynUser.ts
  src/i18n/I18nextManager.ts
  src/icons/EntityIcons.tsx
  src/icons/Icons.tsx
  src/idtype/IDType.ts
  src/idtype/IDTypeManager.ts
  src/plugin/PluginRegistry.ts
  src/ranking/EagerVisynRanking.tsx
  src/ranking/VisynRanking.tsx
  src/ranking/overrides/DatavisynTaggle.tsx
  src/ranking/score/utilities.ts
  src/ranking/smiles/SMILESColumn.tsx
  src/ranking/smiles/SMILESFilterDialog.tsx
  src/ranking/smiles/SMILESRenderer.tsx
  src/ranking/smiles/utils.ts
  src/security/Permission.ts
  src/security/UserSession.ts
  src/utils/Util.stories.tsx
  src/utils/fromNow.ts
  src/views/visyn/demo/VisynDemoView.tsx
  src/vis/EagerVis.tsx
  src/vis/bar/hooks/useGetBarScales.ts
  src/vis/bar/hooks/useGetGroupedBarScales.ts
  src/vis/correlation/CorrelationMatrix.tsx
  src/vis/heatmap/Heatmap.tsx
  src/vis/heatmap/HeatmapRect.tsx
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/utils.ts
  tsconfig.lenient.json
Labels: release: major, dependencies

#537 feat: barvis improvements
  src/vis/bar/BarChart.tsx
  src/vis/bar/SingleBarChart.tsx
  src/vis/bar/barComponents/XAxis.tsx
  src/vis/bar/barTypes/GroupedBars.tsx
  src/vis/bar/barTypes/StackedBars.tsx
  src/vis/bar/hooks/useGetGroupedBarScales.ts
  src/vis/bar/interfaces.ts
  src/vis/bar/utils.ts
Labels: type: feature, vis-type: bar

#539 feat: add mouse icon
  src/icons/Icons.tsx
Labels: release: patch, type: bug

#540 fix: add mantine carousel package to dependencies
  package.json
  playwright.config.ts
Labels: dependencies
