Repository datavisyn/visyn_core, pull requests merged in 2024-10, with the labels that each got.

#551 perf: Adjusted imports for echarts
  src/vis/bar/SingleEChartsBarChart.tsx
  src/vis/vishooks/hooks/index.ts
  src/vis/vishooks/hooks/useChart.ts
Labels: type: feature, type: refactor

#553 feat: Used dimensions from parent to resize plotly
  src/vis/general/InvalidCols.tsx
  src/vis/scatter/ScatterVis.tsx
Labels: type: bug, vis-type: scatter

#550 fix(vis-type: sankey): Handle undefined/missing values
  src/vis/sankey/SankeyVis.tsx
Labels: type: bug

#562 fix: export box plot interfaces
  src/vis/index.ts
Labels: release: patch, type: bug

#561 feat(vis-type: bar): download chart is clipped for long charts
  package.json
  src/vis/bar/BarChart.tsx
  src/vis/bar/SingleEChartsBarChart.tsx
  src/vis/general/DownloadPlotButton.tsx
  src/vis/useCaptureVisScreenshot.ts
Labels: type: feature

#530 feat(vis-type: scatter): improve rendering of scatter plot
  playwright/scatterPlot/04_color.spec.ts
  playwright/scatterPlot/05_shape.spec.ts
  src/hooks/useAsync.tsx
  src/jstat.d.ts
  src/vis/EagerVis.tsx
  src/vis/general/InvalidCols.tsx
  src/vis/general/layoutUtils.ts
  src/vis/general/utils.ts
  src/vis/interfaces.ts
  src/vis/scatter/FastTextMeasure.ts
  src/vis/scatter/Regression.tsx
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/index.ts
  src/vis/scatter/interfaces.ts
  src/vis/scatter/useData.tsx
  src/vis/scatter/useDataPreparation.ts
  src/vis/scatter/useLayout.tsx
  src/vis/scatter/utils.ts
  src/vis/sidebar/NumericalColorButtons.tsx
  src/vis/sidebar/SingleSelect.tsx
  src/vis/stories/Vis/Scatter/ScatterIris.stories.tsx
  src/vis/violin/ViolinVis.tsx
  src/vis/vishooks/hooks/VisHooks.stories.tsx
Labels: release: minor, type: feature

#569 fix: show error message if Vis download fails
  playwright/hexbin/01_general.spec.ts
  src/vis/hexbin/HexbinVis.tsx
  src/vis/useCaptureVisScreenshot.ts
Labels: release: patch, type: bug

#573 fix(vis-type: scatter): add null check in `useData` hook
  src/vis/scatter/useData.tsx
Labels: type: bug

#574 deps: update to yarn@4.5.0
  .yarn/releases/yarn-4.3.0.cjs
  .yarn/releases/yarn-4.5.0.cjs
  .yarnrc.yml
  package.json
Labels: release: patch

#572 fix(vis-type: scatter): Fix SPLOM stats calculation and cleanup
  src/demo/MainApp.tsx
  src/vis/scatter/Regression.tsx
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/interfaces.ts
  src/vis/scatter/utils.ts
  src/vis/stories/Vis/Scatter/ScatterIris.stories.tsx
Labels: type: bug

#576 fix(vis-type: bar): jump to full width after rendering narrow initially using debounced resize observer
  src/vis/vishooks/hooks/useChart.ts
Labels: type: bug, vis-type: bar

#575 feat(vis-type: bar): introduce workers + fix some bugs
  package.json
  src/echarts/useChart.ts
  src/vis/bar/BarChart.tsx
  src/vis/bar/SingleEChartsBarChart.tsx
  src/vis/bar/interfaces/internal/helpers/bar-vis.worker-helper.ts
  src/vis/bar/interfaces/internal/helpers/bar-vis.worker.ts
  src/vis/bar/interfaces/internal/helpers/create-bin-lookup.ts
  src/vis/bar/interfaces/internal/helpers/generate-aggregated-data-lookup.ts
  src/vis/bar/interfaces/internal/helpers/generate-bar-series.test.ts
  src/vis/bar/interfaces/internal/helpers/generate-bar-series.ts
  src/vis/bar/interfaces/internal/helpers/generate-data-table.ts
  src/vis/bar/interfaces/internal/helpers/get-data-for-aggregate-type.test.ts
  src/vis/bar/interfaces/internal/helpers/get-data-for-aggregate-type.ts
  src/vis/bar/interfaces/internal/helpers/get-truncated-text-map.ts
  src/vis/bar/interfaces/internal/helpers/index.ts
  src/vis/bar/interfaces/internal/helpers/normalized-value.test.ts
  src/vis/bar/interfaces/internal/helpers/normalized-value.ts
  src/vis/bar/interfaces/internal/helpers/sort-series.ts
  src/vis/interfaces.ts
  src/vis/stories/Vis/Bar/BarRandom.stories.tsx
Labels: type: bug, vis-type: bar

#594 fix: replace `categoricalColors` with `categoricalColors10`
  playwright/boxPlot/04_subcategory.spec.ts
  src/vis/scatter/ScatterVis.tsx
  src/vis/violin/utils.ts
Labels: type: bug, vis-type: scatter

#604 fix(vis-type: bar): selection is lost when bar plot is sorted
  src/vis/bar/SingleEChartsBarChart.tsx
Labels: type: bug

#606 feat: use `FastTextMeasure` to get the truncated labels
  src/vis/bar/BarChart.tsx
  src/vis/bar/SingleEChartsBarChart.tsx
  src/vis/bar/interfaces/internal/helpers/bar-vis.worker.ts
  src/vis/bar/interfaces/internal/helpers/get-bar-data.ts
  src/vis/bar/interfaces/internal/helpers/get-data-for-aggregate-type.test.ts
  src/vis/bar/interfaces/internal/helpers/get-truncated-text-map.ts
  src/vis/bar/interfaces/internal/helpers/index.ts
  src/vis/bar/interfaces/internal/helpers/sort-series.ts
  src/vis/general/FastTextMeasure.ts
  src/vis/general/index.ts
  src/vis/scatter/useLayout.tsx
  src/vis/stories/explodedData.ts
Labels: type: refactor

#607 fix(vis-type: bar): axis labels when sort state is null
  src/vis/bar/SingleEChartsBarChart.tsx
Labels: release: patch, type: bug

#608 fix: capturing a screenshot is broken for several visualizations
  src/vis/correlation/CorrelationMatrix.tsx
  src/vis/scatter/ScatterVis.tsx
  src/vis/useCaptureVisScreenshot.ts
Labels: release: patch, type: bug

#609 feat(icon): Option for descending sort first + no unsorted state
  src/vis/general/SortIcon.stories.tsx
  src/vis/general/SortIcon.tsx
Labels: type: feature
