Repository datavisyn/visyn_core, pull requests merged in 2024-02, with the labels that each got.

#181 feat: add POSTGRES_PORT to get_default_postgres_url
  visyn_core/settings/utils.py
Labels: release: patch, type: feature

#172 fix: vis is rendered with an invalid config
  src/vis/EagerVis.tsx
  src/vis/heatmap/HeatmapGrid.tsx
  src/vis/heatmap/HeatmapText.tsx
Labels: release: patch, type: bug

#190 Release 8.0.1
  package.json
  requirements.txt
  src/vis/EagerVis.tsx
  src/vis/heatmap/HeatmapGrid.tsx
  src/vis/heatmap/HeatmapText.tsx
  visyn_core/settings/utils.py
Labels: release: patch

#194 Release 8.1.1
  package.json
  src/app/header/DatavisynLogo.tsx
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/utils.ts
Labels: release: patch

#195 fix: more specific `data-testid` in VisynApp header for Cypress tests
  src/app/header/ConfigurationMenu.tsx
  src/app/header/UserMenu.tsx
Labels: release: patch

#196 Release 8.1.2
  cypress/e2e/health-check.cy.ts
  package.json
  src/app/header/ConfigurationMenu.tsx
  src/app/header/UserMenu.tsx
Labels: release: patch

#206 fix: add HEAD method to health endpoint
  visyn_core/server/visyn_server.py
Labels: release: patch, type: bug
