Repository datavisyn/visyn_core, pull requests merged in 2024-06, with the labels that each got.

#319 feat: Sentry integration
  package.json
  src/app/VisynAppProvider.tsx
  src/base/clientConfig.ts
  visyn_core/__init__.py
  visyn_core/sentry/__init__.py
  visyn_core/sentry/sentry_proxy_router.py
  visyn_core/settings/client_config.py
  visyn_core/settings/model.py
Labels: release: patch, type: feature

#335 Release 10.2.0
  .github/workflows/build.yml
  .github/workflows/chromatic.yml
  .storybook/main.js
  chromatic.config.json
  package.json
  requirements.txt
  requirements_dev.txt
  src/app/VisynAppProvider.tsx
  src/base/clientConfig.ts
  src/vis/sidebar/AggregateTypeSelect.tsx
  visyn_core/__init__.py
  visyn_core/sentry/__init__.py
  visyn_core/sentry/sentry_proxy_router.py
  visyn_core/settings/client_config.py
  visyn_core/settings/model.py
Labels: release: minor

#347 feat: add console integration for Sentry
  src/app/VisynAppProvider.tsx
Labels: release: patch, type: feature

#302 feat: add boxplot vis type
  src/vis/EagerVis.tsx
  src/vis/boxplot/index.ts
  src/vis/boxplot/interfaces.ts
  src/vis/interfaces.ts
  src/vis/violin/ViolinSegmentedControl.tsx
  src/vis/violin/ViolinVis.tsx
  src/vis/violin/ViolinVisSidebar.tsx
  src/vis/violin/interfaces.ts
  src/vis/violin/utils.ts
Labels: release: patch, type: feature, vis-type: violin

#346 feat: lazy load plotly where possible
  src/vis/scatter/ScatterVis.tsx
  src/vis/useCaptureVisScreenshot.ts
  src/vis/violin/ViolinVis.tsx
Labels: release: patch

#363 Release 11.0.1
  package.json
  src/vis/general/SortIcon.tsx
Labels: release: patch

#364 feat: add sentry FastAPI integration
  requirements.txt
  visyn_core/server/visyn_server.py
  visyn_core/settings/model.py
Labels: release: patch, type: feature

#369 feat: pin arquero to 5.4.0 because of typing issues
  package.json
Labels: release: patch, dependencies
