Repository datavisyn/visyn_core, pull requests merged in 2024-08, with the labels that each got.

#455 fix(vis-type: scatter): tooltip labels for facets in scatter plot
  src/vis/scatter/utils.ts
Labels: release: minor, type: bug

#465 feat: return 401 if not logged in for loggedinas
  src/security/LoginUtils.ts
  visyn_core/security/jwt_router.py
  visyn_core/tests/test_security_login.py
Labels: release: patch

#472 refactor: improve time complexity for tooltip labels + minor fixes
  src/vis/scatter/utils.ts
Labels: type: refactor, vis-type: scatter

#469 feat(vis-type: scatter): selecting points from multiple facets
  src/vis/scatter/ScatterVis.tsx
Labels: release: minor, type: feature

#474 fix: add null check for the user
  src/app/header/UserMenu.tsx
  src/app/header/VisynHeader.tsx
Labels: release: patch, type: bug

#481 Feature: Facet sorting
  src/vis/EagerVis.tsx
  src/vis/heatmap/interfaces.ts
  src/vis/interfaces.ts
  src/vis/scatter/Regression.tsx
  src/vis/scatter/utils.ts
  src/vis/violin/utils.ts
Labels: type: bug, type: feature

#482 feat: implement bar plot sorting
  src/demo/MainApp.tsx
  src/vis/bar/BarChart.tsx
  src/vis/bar/BarChartSortButton.tsx
  src/vis/bar/SingleEChartsBarChart.tsx
  src/vis/bar/interfaces.ts
  src/vis/general/constants.ts
Labels: type: feature
