Repository datavisyn/visyn_core, pull requests merged in 2024-03, with the labels that each got.

#211 deps(npm): lineupjs@4.10.0
  package.json
  src/demo/MainApp.tsx
  src/demo/randomSurnames.ts
  src/demo/scoresUtils.ts
Labels: release: minor, type: technical debt

#213 fix(ui): font size of mantine anchors (links)
  src/app/login/UserStoreUIMap.tsx
  src/app/login/VisynLoginMenu.tsx
Labels: release: patch, type: bug

#221 Release 9.1.0
  package.json
  src/app/login/UserStoreUIMap.tsx
  src/app/login/VisynLoginMenu.tsx
  src/demo/MainApp.tsx
  src/demo/randomSurnames.ts
  src/demo/scoresUtils.ts
  src/vis/bar/barComponents/XAxis.tsx
  src/vis/bar/barComponents/YAxis.tsx
  src/vis/legend/ColorLegend.tsx
  src/vis/legend/ColorLegendVert.tsx
  src/vis/sidebar/VisTypeSelect.tsx
Labels: release: minor

#220 fix: stale state in vis when changing vis type
  src/vis/EagerVis.tsx
Labels: release: patch, type: bug

#226 Release 9.1.1
  package.json
  src/vis/EagerVis.tsx
Labels: release: patch

#233 Release 9.1.2
  package.json
  src/vis/scatter/ScatterVis.tsx
Labels: release: patch

#234 refactor: rename data-cy to data-testid
  src/app/login/VisynLoginForm.tsx
Labels: release: major

#235 Release v9.1.3
  package.json
  src/app/login/VisynLoginForm.tsx
Labels: release: patch

#240 fix(scatterplot): use label in selection labels
  src/vis/scatter/utils.ts
Labels: release: patch, type: refactor

#241 Release 9.2.0
  package.json
  src/app/constants.tsx
  src/demo/randomSurnames.ts
  src/icons/EntityIcons.tsx
  src/icons/Icons.tsx
  src/icons/index.ts
  src/types.ts
  src/utils/colors.ts
  src/utils/index.ts
  src/vis/bar/hooks/useGetGroupedBarScales.ts
  src/vis/heatmap/Heatmap.tsx
  src/vis/scatter/utils.ts
  tests/exports.test.ts
Labels: release: minor
