Repository datavisyn/visyn_core, pull requests merged in 2024-04, with the labels that each got.

#255 Release 9.2.1
  package.json
  src/app/constants.tsx
  src/icons/EntityIcons.tsx
  src/icons/Icons.tsx
Labels: release: patch

#265 Release 9.2.2
  cypress/e2e/health-check.cy.ts
  package.json
  src/app/constants.tsx
  src/icons/EntityIcons.tsx
  src/icons/Icons.tsx
Labels: release: patch

#262 feat: add possibility to insert score column after given column in ranking
  src/ranking/overrides/DatavisynTaggle.tsx
Labels: type: feature

#257 chore: remove usage of flask
  Makefile
  requirements.txt
  requirements_dev.txt
  src/idtype/IDTypeManager.ts
  src/security/LoginUtils.ts
  src/utils/XlsxUtils.ts
  visyn_core/__init__.py
  visyn_core/dbmanager.py
  visyn_core/dbmigration/env.py
  visyn_core/dbmigration/manager.py
  visyn_core/dbmigration/router.py
  visyn_core/dbview.py
  visyn_core/id_mapping/idtype_api.py
  visyn_core/id_mapping/manager.py
  visyn_core/middleware/close_web_sessions_middleware.py
  visyn_core/middleware/exception_handler_middleware.py
  visyn_core/rdkit/models.py
  visyn_core/security/jwt_router.py
  visyn_core/server/mainapp.py
  visyn_core/server/utils.py
  visyn_core/server/visyn_server.py
  visyn_core/settings/router.py
  visyn_core/telemetry/__init__.py
  visyn_core/tests/fixtures/postgres_db.py
  visyn_core/tests/test_main_app.py
  visyn_core/tests/test_security_login.py
  visyn_core/tests/test_telemetry.py
  visyn_core/tests/test_xlsx.py
  visyn_core/xlsx.py
Labels: type: refactor

#266 refactor: rename labels of filter buttons
  src/vis/sidebar/FilterButtons.tsx
Labels: release: patch, type: refactor

#261 fix(vis): duplicate option values in scatterplot sidebar select
  src/vis/sidebar/MultiSelect.tsx
Labels: priority: high, release: patch, type: bug

#267 fix(vis): violin vis selection events
  src/vis/sidebar/MultiSelect.tsx
  src/vis/stories/Iris.stories.tsx
  src/vis/stories/Vis/Bar/BarRandom.stories.tsx
  src/vis/stories/Vis/Correlation/CorrelationIris.stories.tsx
  src/vis/stories/Vis/Heatmap/HeatmapRandom.stories.tsx
  src/vis/stories/Vis/Hexbin/HexbinRandom.stories.tsx
  src/vis/stories/Vis/Raincloud/RaincloudRandom.stories.tsx
  src/vis/stories/Vis/Scatter/ScatterRandom.stories.tsx
  src/vis/stories/Vis/Violin/ViolinIris.stories.tsx
  src/vis/violin/ViolinVis.tsx
  src/vis/violin/utils.ts
Labels: type: bug

#270 Release 10.0.0
  Makefile
  package.json
  requirements.txt
  requirements_dev.txt
  src/idtype/IDTypeManager.ts
  src/ranking/overrides/DatavisynTaggle.tsx
  src/security/LoginUtils.ts
  src/utils/XlsxUtils.ts
  src/vis/sidebar/FilterButtons.tsx
  src/vis/sidebar/MultiSelect.tsx
  src/vis/stories/Iris.stories.tsx
  src/vis/stories/Vis/Bar/BarRandom.stories.tsx
  src/vis/stories/Vis/Correlation/CorrelationIris.stories.tsx
  src/vis/stories/Vis/Heatmap/HeatmapRandom.stories.tsx
  src/vis/stories/Vis/Hexbin/HexbinRandom.stories.tsx
  src/vis/stories/Vis/Raincloud/RaincloudRandom.stories.tsx
  src/vis/stories/Vis/Scatter/ScatterRandom.stories.tsx
  src/vis/stories/Vis/Violin/ViolinIris.stories.tsx
  src/vis/violin/ViolinVis.tsx
  src/vis/violin/utils.ts
  visyn_core/__init__.py
  visyn_core/dbmanager.py
  visyn_core/dbmigration/env.py
  visyn_core/dbmigration/manager.py
  visyn_core/dbmigration/router.py
  visyn_core/dbview.py
  visyn_core/id_mapping/idtype_api.py
  visyn_core/id_mapping/manager.py
  visyn_core/middleware/close_web_sessions_middleware.py
  visyn_core/middleware/exception_handler_middleware.py
  visyn_core/rdkit/models.py
  visyn_core/security/jwt_router.py
  visyn_core/server/mainapp.py
  visyn_core/server/utils.py
  visyn_core/server/visyn_server.py
  visyn_core/settings/router.py
  visyn_core/telemetry/__init__.py
  visyn_core/tests/fixtures/postgres_db.py
  visyn_core/tests/test_main_app.py
  visyn_core/tests/test_security_login.py
  visyn_core/tests/test_telemetry.py
  visyn_core/tests/test_xlsx.py
  visyn_core/xlsx.py
Labels: release: major

#273 refactor: replace `.api_route()` with explicit method functions
  visyn_core/id_mapping/idtype_api.py
  visyn_core/security/jwt_router.py
  visyn_core/server/mainapp.py
Labels: release: patch, type: refactor

#280 Release 10.0.1
  package.json
  src/icons/Icons.tsx
  src/scss/vendors/_lineup.scss
  visyn_core/id_mapping/idtype_api.py
  visyn_core/security/jwt_router.py
  visyn_core/server/mainapp.py
Labels: release: patch
