Repository datavisyn/visyn_core, pull requests merged in 2024-12, with the labels that each got.

#656 fix: VariableSizeList typing
  src/vis/bar/BarChart.tsx
Labels: release: patch

#649 feat: Celery integration
  Makefile
  docker-compose.yml
  requirements.txt
  visyn_core/celery/app.py
  visyn_core/celery/main.py
  visyn_core/dev_app.py
  visyn_core/dev_celery.py
  visyn_core/manager.py
  visyn_core/server/utils.py
  visyn_core/server/visyn_server.py
  visyn_core/settings/model.py
  visyn_core/tests/fixtures/app.py
  visyn_core/tests/test_celery.py
Labels: release: minor, type: feature

#665 fix(vis-type: bar): focus facet selector + sort facets alphabetically
  src/vis/bar/BarChart.tsx
  src/vis/bar/components/FocusFacetSelector.tsx
Labels: release: patch, type: bug
