Repository datavisyn/visyn_core, pull requests merged in 2024-01, with the labels that each got.

#139 feat: debug log for access_token in oauth security store
  visyn_core/security/store/oauth2_security_store.py
Labels: release: patch, type: feature

#140 Fix: tooltip bug in violin plot
  src/vis/stories/fetchIrisData.tsx
  src/vis/violin/ViolinVis.tsx
Labels: type: bug

#130 Handle null value only columns in raincloud plot
  src/vis/raincloud/Raincloud.tsx
Labels: type: bug

#142 Release 7.0.1
  package.json
  src/vis/raincloud/Raincloud.tsx
  src/vis/violin/ViolinVis.tsx
  visyn_core/security/store/oauth2_security_store.py
  visyn_core/settings/model.py
  visyn_core/settings/utils.py
Labels: release: patch

#141 feat: use label column in Vis tooltips
  src/vis/general/layoutUtils.ts
  src/vis/interfaces.ts
  src/vis/raincloud/Raincloud.tsx
  src/vis/raincloud/RaincloudGrid.tsx
  src/vis/raincloud/utils.ts
  src/vis/scatter/utils.ts
Labels: release: minor, type: feature

#143 Release 7.0.2
  package.json
  src/vis/general/layoutUtils.ts
  src/vis/interfaces.ts
  src/vis/raincloud/Raincloud.tsx
  src/vis/raincloud/RaincloudGrid.tsx
  src/vis/raincloud/utils.ts
  src/vis/scatter/utils.ts
Labels: release: patch

#155 feat: add driver option to get_default_postgres_url
  visyn_core/settings/utils.py
Labels: release: patch, type: feature

#156 Release 7.0.3
  .github/dependabot.yml
  .gitignore
  package.json
  visyn_core/settings/utils.py
  yarn.lock
Labels: release: patch

#157 feat: add debug logging to alb_security_store
  visyn_core/security/store/alb_security_store.py
  visyn_core/tests/test_security_login.py
Labels: release: patch, type: feature
