Repository datavisyn/visyn_core, pull requests merged in 2024-07, with the labels that each got.

#392 fix(vis): histogram selection logic for scatter vis
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/utils.ts
Labels: release: patch, vis-type: scatter

#393 Release 11.2.0
  package.json
  src/icons/Icons.tsx
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/utils.ts
Labels: release: minor

#420 feat(vis): focus facet selector for bar chart
  src/vis/bar/BarChart.tsx
  src/vis/bar/BarVis.tsx
  src/vis/bar/README.md
  src/vis/bar/SingleBarChart.tsx
  src/vis/bar/barComponents/FocusFacetSelector.tsx
  src/vis/bar/interfaces.ts
Labels: release: minor, type: feature, vis-type: bar

#428 fix(vis): make bar chart interface properties optional
  src/vis/bar/BarChart.tsx
  src/vis/bar/interfaces.ts
Labels: type: bug

#435 fix(scatter): Re-enable sequential and divergent color scales
  src/vis/bar/BarVisSidebar.tsx
  src/vis/hexbin/HexbinVisSidebar.tsx
  src/vis/scatter/ColorSelect.tsx
  src/vis/scatter/ScatterVisSidebar.tsx
  src/vis/sidebar/AggregateTypeSelect.tsx
  src/vis/sidebar/SingleSelect.tsx
  src/vis/violin/ViolinVisSidebar.tsx
Labels: release: patch, type: bug
