Repository datavisyn/visyn_core, pull requests merged in 2024-05, with the labels that each got.

#279 feat: capture visualization snapshot
  package.json
  src/demo/MainApp.tsx
  src/icons/Icons.tsx
  src/vis/EagerVis.tsx
  src/vis/bar/BarChart.tsx
  src/vis/bar/BarVis.tsx
  src/vis/correlation/CorrelationMatrix.tsx
  src/vis/correlation/CorrelationVis.tsx
  src/vis/general/DownloadPlotButton.tsx
  src/vis/heatmap/Heatmap.tsx
  src/vis/heatmap/HeatmapGrid.tsx
  src/vis/heatmap/HeatmapVis.tsx
  src/vis/hexbin/HexbinVis.tsx
  src/vis/index.ts
  src/vis/interfaces.ts
  src/vis/raincloud/RaincloudVis.tsx
  src/vis/sankey/SankeyVis.tsx
  src/vis/scatter/ScatterVis.tsx
  src/vis/useCaptureVisScreenshot.ts
  src/vis/violin/ViolinVis.tsx
Labels: release: minor, type: feature

#275 feat: Scattervis facets and regression line
  package.json
  src/demo/MainApp.tsx
  src/vis/EagerVis.tsx
  src/vis/VisSidebarWrapper.tsx
  src/vis/bar/BarChart.tsx
  src/vis/bar/BarVisSidebar.tsx
  src/vis/bar/hooks/useGetBarScales.ts
  src/vis/bar/hooks/useGetGroupedBarScales.ts
  src/vis/bar/interfaces.ts
  src/vis/bar/utils.ts
  src/vis/general/layoutUtils.ts
  src/vis/interfaces.ts
  src/vis/raincloud/rain/WheatPlot.tsx
  src/vis/scatter/OpacitySlider.tsx
  src/vis/scatter/Regression.tsx
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/ScatterVisSidebar.tsx
  src/vis/scatter/interfaces.ts
  src/vis/scatter/utils.ts
  src/vis/sidebar/FilterButtons.tsx
  src/vis/sidebar/MultiSelect.tsx
  src/vis/sidebar/SingleSelect.tsx
  src/vis/stories/Iris.stories.tsx
  src/vis/stories/Vis/Bar/BarDocs.stories.mdx
  src/vis/stories/Vis/Bar/BarRandom.stories.tsx
  src/vis/stories/Vis/Scatter/ScatterIris.stories.tsx
  src/vis/stories/Vis/Scatter/ScatterRandom.stories.tsx
Labels: type: feature

#304 fix(vis): XY Labels in scatter vis hovertext
  src/vis/scatter/Regression.tsx
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/utils.ts
Labels: release: patch, vis-type: scatter

#310 Fix scatter vis label mapping
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/utils.ts
Labels: type: bug, vis-type: scatter

#278 fix: truncate long legend names
  src/vis/bar/barComponents/Legend.tsx
  src/vis/scatter/utils.ts
  src/vis/sidebar/SingleSelect.tsx
Labels: release: minor, type: bug

#277 feat: add toggle legend switch to scatter plot
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/interfaces.ts
Labels: release: minor, type: feature

#312 Release 10.1.0
  package.json
  requirements.txt
  requirements_dev.txt
  src/demo/MainApp.tsx
  src/icons/EntityIcons.tsx
  src/icons/Icons.tsx
  src/vis/EagerVis.tsx
  src/vis/VisSidebarWrapper.tsx
  src/vis/bar/BarChart.tsx
  src/vis/bar/BarVis.tsx
  src/vis/bar/BarVisSidebar.tsx
  src/vis/bar/barComponents/Legend.tsx
  src/vis/bar/hooks/useGetBarScales.ts
  src/vis/bar/hooks/useGetGroupedBarScales.ts
  src/vis/bar/interfaces.ts
  src/vis/bar/utils.ts
  src/vis/correlation/CorrelationMatrix.tsx
  src/vis/correlation/CorrelationVis.tsx
  src/vis/general/DownloadPlotButton.tsx
  src/vis/general/constants.ts
  src/vis/general/layoutUtils.ts
  src/vis/heatmap/Heatmap.tsx
  src/vis/heatmap/HeatmapGrid.tsx
  src/vis/heatmap/HeatmapVis.tsx
  src/vis/hexbin/HexbinVis.tsx
  src/vis/index.ts
  src/vis/interfaces.ts
  src/vis/raincloud/RaincloudVis.tsx
  src/vis/raincloud/rain/WheatPlot.tsx
  src/vis/sankey/SankeyVis.tsx
  src/vis/scatter/OpacitySlider.tsx
  src/vis/scatter/Regression.tsx
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/ScatterVisSidebar.tsx
  src/vis/scatter/interfaces.ts
  src/vis/scatter/utils.ts
  src/vis/sidebar/FilterButtons.tsx
  src/vis/sidebar/MultiSelect.tsx
  src/vis/sidebar/SingleSelect.tsx
  src/vis/sidebar/index.ts
  src/vis/stories/Iris.stories.tsx
  src/vis/stories/Vis/Bar/BarDocs.stories.mdx
  src/vis/stories/Vis/Bar/BarRandom.stories.tsx
  src/vis/stories/Vis/Scatter/ScatterIris.stories.tsx
  src/vis/stories/Vis/Scatter/ScatterRandom.stories.tsx
  src/vis/useCaptureVisScreenshot.ts
  src/vis/violin/ViolinOverlayButtons.tsx
  src/vis/violin/ViolinSegmentedControl.tsx
  src/vis/violin/ViolinVis.tsx
  src/vis/violin/ViolinVisSidebar.tsx
  src/vis/violin/interfaces.ts
  src/vis/violin/utils.ts
Labels: release: minor
