Repository datavisyn/visyn_core, pull requests merged in 2025-01, with the labels that each got.

#671 fix: `@use` lineupengine vars to allow overriding them
  src/scss/vendors/_lineup.scss
Labels: release: patch, type: bug

#670 fix: add back `showLabelLimit` option to scatter visualization
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/ScatterVisSidebar.tsx
  src/vis/scatter/interfaces.ts
  src/vis/scatter/useData.tsx
  src/vis/scatter/useLayout.tsx
Labels: release: minor, type: refactor

#680 feat: Add skip/preventDefault conditions to useWheel
  src/vis/vishooks/hooks/useWheel.ts
  src/vis/vishooks/hooks/useZoom.ts
  src/vis/vishooks/interfaces.ts
  src/vis/vishooks/normalizeWheelEvent.ts
Labels: type: feature

#679 feat: useTransformScale now supports ranged based transforms
  src/vis/vishooks/hooks/useTransformScale.ts
Labels: release: patch, type: feature

#674 deps: upgrade to fastapi 0.115.6 and ruff 0.9.1
  requirements.txt
  requirements_dev.txt
  visyn_core/dbview.py
  visyn_core/plugin/registry.py
  visyn_core/rdkit/img_api.py
  visyn_core/security/manager.py
  visyn_core/tests/fixtures/app.py
Labels: release: minor, dependencies

#685 deps: update Mantine to 7.16
  package.json
  src/demo/MainApp.tsx
Labels: release: major, dependencies

#687 feat: export Vector3 and Matrix4x4
  src/vis/vishooks/math/matrix4x4.ts
  src/vis/vishooks/math/vector3.ts
Labels: release: patch

#693 fix(vis-type: bar): label layouting issue in the bar plot
  src/vis/bar/BarChart.tsx
Labels: release: patch, type: bug

#707 deps(pip): ease redis version range
  requirements.txt
Labels: type: technical debt

#695 feat: add bundlesize check
  package.json
  src/components/HelpHoverCard.tsx
  src/components/PermissionChooser.tsx
  src/demo/MainApp.tsx
  src/demo/scoresUtils.ts
  src/icons/Icons.tsx
  src/ranking/score/interfaces.ts
  src/ranking/score/utilities.ts
  src/ranking/smiles/SMILESColumn.tsx
  src/ranking/smiles/SMILESFilterDialog.tsx
  src/ranking/smiles/utils.ts
  src/vis/VisSidebarWrapper.tsx
  src/vis/bar/components/FocusFacetSelector.tsx
  src/vis/correlation/CorrelationMatrix.tsx
  src/vis/correlation/CorrelationVisSidebar.tsx
  src/vis/general/ErrorMessage.tsx
  src/vis/general/WarningMessage.tsx
  src/vis/heatmap/HeatmapGrid.tsx
  src/vis/hexbin/HexbinVis.tsx
  src/vis/index.ts
  src/vis/interfaces.ts
  src/vis/lineupWrapper/LineupVisWrapper.ts
  src/vis/lineupWrapper/index.ts
  src/vis/sankey/SankeyVis.tsx
  src/vis/sankey/utils.ts
  src/vis/scatter/LabelingOptions.tsx
  src/vis/sidebar/utils.tsx
  src/vis/useCaptureVisScreenshot.ts
  src/vis/violin/utils.ts
  src/vis/vishooks/math/matrix4x4.ts
  src/vis/vishooks/math/vector3.ts
  tests/exports.test.ts
Labels: release: major, type: feature, type: technical debt
