Repository datavisyn/visyn_core, pull requests merged in 2025-03, with the labels that each got.

#737 feat: export vis LegendItem
  src/vis/general/index.ts
Labels: release: minor, type: feature

#738 feat: protect all routes by default and add sentry init
  src/app/VisynAppProvider.tsx
  visyn_core/__init__.py
  visyn_core/middleware/fastapi_metrics_middleware.py
  visyn_core/plugin/model.py
  visyn_core/security/dependencies.py
  visyn_core/security/manager.py
  visyn_core/sentry/sentry_proxy_router.py
  visyn_core/server/visyn_server.py
  visyn_core/settings/model.py
  visyn_core/tests/fixtures/app.py
  visyn_core/tests/test_security_login.py
Labels: release: major, type: feature

#739 deps: upgrade to visyn_scripts 13 and remove Mantine 6
  package.json
  src/app/VisynAppProvider.tsx
  src/app/constants.tsx
  src/demo/index.initialize.tsx
Labels: release: major, dependencies

#745 deps: update to visyn_scripts 13.1.0
  package.json
  visyn_core/__init__.py
Labels: release: patch, dependencies

#747 feat: use traces_sampler to ignore certain paths from being sampled
  visyn_core/server/visyn_server.py
Labels: release: patch, type: feature

#748 feat: consume ca_certs for Sentry frontend proxy
  visyn_core/sentry/sentry_proxy_router.py
  visyn_core/settings/model.py
Labels: release: minor, type: feature

#750 feat: increate Sentry proxy timeout and only return select headers
  visyn_core/sentry/sentry_proxy_router.py
  visyn_core/settings/model.py
Labels: release: patch, type: feature

#753 feat: allow optional Sentry proxy headers
  visyn_core/sentry/sentry_proxy_router.py
Labels: release: patch, type: bug

#755 feat: add Sentry demo configuration
  src/demo/index.initialize.tsx
  visyn_core/sentry/sentry_proxy_router.py
Labels: release: patch, type: feature

#757 feat: add VisynEvents to send global events, incl. better Sentry integration
  src/app/VisynAppContext.tsx
  src/app/VisynAppProvider.tsx
  src/app/VisynEvents.ts
  src/app/header/AboutAppModal.tsx
  src/app/header/VisynHeader.stories.tsx
  src/app/index.ts
  src/base/AppContext.ts
  src/base/VisynEnv.ts
  src/base/event.ts
  src/base/index.ts
  src/demo/MainApp.tsx
  src/demo/index.initialize.tsx
  src/hooks/index.ts
  src/hooks/useVisynEventCallback.tsx
  src/hooks/useVisynEventValue.tsx
  src/hooks/useVisynUser.ts
  src/security/UserSession.ts
  src/security/watcher.ts
  visyn_core/plugin/parser.py
  visyn_core/server/visyn_server.py
Labels: release: minor, type: feature

#763 feat: add main_app parameter to celery
  src/app/VisynAppProvider.tsx
  visyn_core/__init__.py
  visyn_core/celery/app.py
  visyn_core/dev_celery.py
  visyn_core/sentry/sentry_integration.py
  visyn_core/server/visyn_server.py
Labels: release: minor, type: feature

#752 feat: parse commands after init_app such that everything is loaded
  src/base/clientConfig.ts
  visyn_core/dbmigration/manager.py
  visyn_core/server/visyn_server.py
  visyn_core/settings/client_config.py
  visyn_core/settings/model.py
  visyn_core/tests/fixtures/app.py
  visyn_core/tests/test_settings.py
Labels: release: minor, type: bug
