Repository datavisyn/visyn_core, pull requests merged in 2025-02, with the labels that each got.

#690 feat: make scatter plot legends clickable
  src/utils/indicesOf.ts
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/useData.tsx
  src/vis/scatter/useDataPreparation.ts
Labels: release: minor, type: feature

#716 fix: removed use-deep-compare-effect, removed Awaited type
  package.json
  src/hooks/useAsync.tsx
Labels: release: patch, type: bug

#717 feat: add waitForClientConfig flag to allow skipping the wait for the clientConfig
  src/app/VisynAppProvider.tsx
  src/demo/index.initialize.tsx
Labels: release: minor, type: feature

#722 feat: update categorical colors and export muted versions
  src/utils/colors.ts
Labels: release: minor, type: feature, type: refactor

#730 feat: add arbitrary properties to user object, i.e. mapped from the JWT payload
  src/app/header/VisynHeader.stories.tsx
  src/security/constants.ts
  src/security/interfaces.ts
  visyn_core/security/manager.py
  visyn_core/security/model.py
  visyn_core/security/store/alb_security_store.py
  visyn_core/security/store/no_security_store.py
  visyn_core/security/store/oauth2_security_store.py
  visyn_core/settings/model.py
  visyn_core/tests/test_security_login.py
Labels: release: minor, type: feature

#726 feat: Added fastTextEllipsis function
  src/vis/general/FastTextMeasure.ts
Labels: type: feature
