Repository datavisyn/visyn_core, pull requests merged in 2025-05, with the labels that each got.

#800 fix: use @types/plotly.js for plotly.js-dist-min
  package.json
  src/plotly/index.tsx
Labels: release: patch

#802 feat: useAsync and useTriggerFrame fixes
  package.json
  src/hooks/useAsync.tsx
  src/hooks/useDepsStabilizer.ts
  src/vis/vishooks/hooks/useTriggerFrame.ts
Labels: release: minor, type: feature

#799 feat: Enable Python logger for RDKit
  visyn_core/rdkit/img_api.py
Labels: release: patch, type: feature, python

#805 feat: set Sentry profiles_sample_rate to 0
  visyn_core/sentry/sentry_integration.py
Labels: release: patch

#804 fix(vis): scatter plot legend toggle for splom
  src/vis/scatter/useData.tsx
  src/vis/scatter/useDataPreparation.ts
Labels: release: patch, type: bug

#808 feat: remove Bearer prefix from access token if exists
  visyn_core/security/store/oauth2_security_store.py
Labels: release: patch, type: feature

#811 feat: expand OAuth2 Security Store with ability to try multiple token headers
  visyn_core/security/store/oauth2_security_store.py
  visyn_core/settings/model.py
  visyn_core/tests/test_security_login.py
Labels: release: patch, type: feature

#814 fix: enable support for iterating through multiple headers even if exceptions are thrown
  visyn_core/security/store/oauth2_security_store.py
  visyn_core/settings/model.py
  visyn_core/tests/test_security_login.py
Labels: release: patch
